### ISSUE TITLE
undefined method `has_key?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by jeffmccune** [GeoffWilliams/ncedit#3]
Hi Geoff, I'm using ncedit on site with a customer to setup some basic code manager things post-install.  Great work on the tool!

I recently had to re-install PE 2016.4.3 in their sandbox environment and now my previously working script is failing on this stacktrace:

```
Group PE Master found, getting definition
undefined method `has_key?' for nil:NilClass
undefined method `has_key?' for nil:NilClass (NoMethodError)
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:253:in `ensure_param'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:297:in `block (2 levels) in ensure_classes_and_params'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:295:in `each'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:295:in `block in ensure_classes_and_params'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:291:in `each'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:291:in `ensure_classes_and_params'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:207:in `block in batch'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:190:in `each'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/lib/ncedit/cmd.rb:190:in `batch'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/exe/ncedit:77:in `block (3 levels) in <top (required)>'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/escort-0.4.0/lib/escort/app.rb:68:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/escort-0.4.0/lib/escort/app.rb:68:in `execute_action'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/escort-0.4.0/lib/escort/app.rb:55:in `execute'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/escort-0.4.0/lib/escort/app.rb:6:in `create'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ncedit-0.1.0/exe/ncedit:9:in `<top (required)>'
/opt/puppetlabs/puppet/bin/ncedit:23:in `load'
/opt/puppetlabs/puppet/bin/ncedit:23:in `<main>'
Escort app failed to execute successfully, due to unknown error
```

The command I'm trying to run is:

```
++ mktemp
+ ncdatafile=/tmp/tmp.CWMnUKHikS/tmp.UhN9AsARd5
+ echo '---
PE Master:
  classes:
    pe_r10k:
      r10k_basedir: /etc/puppetlabs/code/environments
      remote: ssh://git@stash-ess.acme.com:7999/pe/modules.git
      git_settings:
        provider: rugged
        private_key: /etc/puppetlabs/puppetserver/ssh/id-all_repo.rsa
      deploy_settings:
        purge_levels:
          - environment
          - puppetfile'
+ ncedit --verbosity debug batch --yaml-file /tmp/tmp.CWMnUKHikS/tmp.UhN9AsARd5
```

The business purpose is to programmatically set the r10k purge level for this customer.
